### ISSUE TITLE
Tests fail

### ISSUE THREAD

**Issue by ethack** [activecm/rita#181]
This was bad form on my part to merge code without running tests (immediately after we got working tests even). I'll get better at remembering and eventually we'll have them automated. I just ran them and then did `git bisect` to find the first commit that the tests fail in.

Tests pass: 8e37eeb90022ff4a5a85544cd1a6e994769f2681
Tests fail: aedfaae9d89950eefeddcda2ce3b44815143cf67

FWIW, tests also fail for the current dev HEAD f00f6639d083331f08e74e2d9507a6920a9a74a7 with a different output.

Test output for aedfaae9d89950eefeddcda2ce3b44815143cf67:
```
--- FAIL: TestAnalysis (0.01s)
	beacon_test.go:57: 0 - PASS:
			Expected Score: 0.990000 < x < 1.000000
			Description: Perfect Beacon every 30 minutes... Starts at 0 (midnight) ends at 86400 (+24 hours)

			UconnID:	ObjectIdHex("")
			TS_iRange:	0
			TS_iMode:	1800
			TS_iModeCount:	48
			TS_intervals:	[1800]
			TS_intervalCounts:	[48]
			TS_iDispersion:	0
			TS_iSkew:	0
			TS_duration:	1
			TS_score:	1
			DS_range:	0
			DS_mode:	4
			DS_modeCount:	3
			DS_sizes:	[4]
			DS_sizeCounts:	[3]
			DS_dispersion:	0
			DS_skew:	0
			DS_score:	0.9999796546374711
			Score:	0.9999898273187355

	beacon_test.go:57: 1 - PASS:
			Expected Score: 0.950000 < x < 1.000000
			Description: Beacon every 30 minutes... Starts at 0 (midnight) ends 60 minutes before next midnight

			UconnID:	ObjectIdHex("")
			TS_iRange:	0
			TS_iMode:	1800
			TS_iModeCount:	47
			TS_intervals:	[1800]
			TS_intervalCounts:	[47]
			TS_iDispersion:	0
			TS_iSkew:	0
			TS_duration:	1
			TS_score:	1
			DS_range:	0
			DS_mode:	4
			DS_modeCount:	3
			DS_sizes:	[4]
			DS_sizeCounts:	[3]
			DS_dispersion:	0
			DS_skew:	0
			DS_score:	0.9999796546374711
			Score:	0.9999898273187355

	beacon_test.go:57: 2 - PASS:
			Expected Score: 0.950000 < x < 1.000000
			Description: Beacon every 30 minutes... Starts at 8:00 ends at 16:00

			UconnID:	ObjectIdHex("")
			TS_iRange:	0
			TS_iMode:	1800
			TS_iModeCount:	16
			TS_intervals:	[1800]
			TS_intervalCounts:	[16]
			TS_iDispersion:	0
			TS_iSkew:	0
			TS_duration:	1
			TS_score:	1
			DS_range:	0
			DS_mode:	4
			DS_modeCount:	3
			DS_sizes:	[4]
			DS_sizeCounts:	[3]
			DS_dispersion:	0
			DS_skew:	0
			DS_score:	0.9999796546374711
			Score:	0.9999898273187355

	beacon_test.go:57: 3 - PASS:
			Expected Score: 0.950000 < x < 1.000000
			Description: Beacon every 10 seconds... Starts at 9:00 ends at 10:00

			UconnID:	ObjectIdHex("")
			TS_iRange:	0
			TS_iMode:	10
			TS_iModeCount:	360
			TS_intervals:	[10]
			TS_intervalCounts:	[360]
			TS_iDispersion:	0
			TS_iSkew:	0
			TS_duration:	1
			TS_score:	1
			DS_range:	0
			DS_mode:	4
			DS_modeCount:	3
			DS_sizes:	[4]
			DS_sizeCounts:	[3]
			DS_dispersion:	0
			DS_skew:	0
			DS_score:	0.9999796546374711
			Score:	0.9999898273187355

	beacon_test.go:57: 4 - FAIL:
			Expected Score: 0.900000 < x < 1.000000
			Description: Beacon every 1 hour... Starts at 0 (midnight) ends at 86400 (+24 hours)... Noise added to each timestamp: Gaussian Mu=0 Sigma=100

			UconnID:	ObjectIdHex("")
			TS_iRange:	2071
			TS_iMode:	1798
			TS_iModeCount:	1
			TS_intervals:	[1798 3393 3461 3623 3652 3710 3722 3426 3460 3494 3602 3654 3691 3434 3558 3674 3869 3421 3463 3510 3637 3665 3679 3723]
			TS_intervalCounts:	[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
			TS_iDispersion:	100
			TS_iSkew:	-0.5211267605633803
			TS_duration:	1
			TS_score:	0.49295774647887325
			DS_range:	2
			DS_mode:	4
			DS_modeCount:	6
			DS_sizes:	[4 6]
			DS_sizeCounts:	[6 3]
			DS_dispersion:	0
			DS_skew:	0
			DS_score:	0.9999796546374711
			Score:	0.7464687005581722

	beacon_test.go:57: 5 - PASS:
			Expected Score: 0.900000 < x < 1.000000
			Description: Perfect Beacon every 60 minutes... Connects twice every time

			UconnID:	ObjectIdHex("")
			TS_iRange:	3596
			TS_iMode:	2
			TS_iModeCount:	25
			TS_intervals:	[2 3598]
			TS_intervalCounts:	[25 24]
			TS_iDispersion:	0
			TS_iSkew:	0
			TS_duration:	1
			TS_score:	1
			DS_range:	0
			DS_mode:	4
			DS_modeCount:	3
			DS_sizes:	[4]
			DS_sizeCounts:	[3]
			DS_dispersion:	0
			DS_skew:	0
			DS_score:	0.9999796546374711
			Score:	0.9999898273187355

	beacon_test.go:57: 6 - FAIL:
			Expected Score: 0.000000 < x < 0.700000
			Description: Connection happens a lot... but not a beacon

			UconnID:	ObjectIdHex("")
			TS_iRange:	1
			TS_iMode:	1
			TS_iModeCount:	9
			TS_intervals:	[1 2]
			TS_intervalCounts:	[9 2]
			TS_iDispersion:	0
			TS_iSkew:	0
			TS_duration:	1
			TS_score:	1
			DS_range:	98
			DS_mode:	2
			DS_modeCount:	1
			DS_sizes:	[2 3 4 43 100]
			DS_sizeCounts:	[1 1 1 1 1]
			DS_dispersion:	2
			DS_skew:	0.95
			DS_score:	0.6624898273187355
			Score:	0.8312449136593677

	beacon_test.go:57: 7 - PASS:
			Expected Score: 0.000000 < x < 0.500000
			Description: Not a beacon.

			UconnID:	ObjectIdHex("")
			TS_iRange:	50328
			TS_iMode:	2
			TS_iModeCount:	1
			TS_intervals:	[2 5 8 47 70 50330]
			TS_intervalCounts:	[1 1 1 1 1 1]
			TS_iDispersion:	42
			TS_iSkew:	-0.2923076923076923
			TS_duration:	1
			TS_score:	0.5692307692307692
			DS_range:	50462
			DS_mode:	10
			DS_modeCount:	1
			DS_sizes:	[10 15 23 70 50400 50470 50472]
			DS_sizeCounts:	[1 1 1 1 1 1 1]
			DS_dispersion:	60
			DS_skew:	0.9981366582750213
			DS_score:	0.33390358383533725
			Score:	0.45156717653305317

FAIL
FAIL	github.com/ocmdev/rita/analysis/beacon	0.028s
```

Test output for f00f6639d083331f08e74e2d9507a6920a9a74a7 (current dev branch):
```
Failed to config, exiting--- FAIL: TestAnalysis (0.00s)
panic: Invalid character(s) found in major number "undefined" [recovered]
	panic: Invalid character(s) found in major number "undefined"

goroutine 19 [running]:
testing.tRunner.func1(0xc4200fa0f0)
	/usr/local/Cellar/go/1.9.2/libexec/src/testing/testing.go:711 +0x2d2
panic(0x11ebae0, 0xc420077a90)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/panic.go:491 +0x283
github.com/ocmdev/rita/database.InitMockResources(0x0, 0x0, 0x13247b2)
	/Users/ethan/go/src/github.com/ocmdev/rita/database/mock.go:19 +0x2ea
github.com/ocmdev/rita/analysis/beacon.TestAnalysis(0xc4200fa0f0)
	/Users/ethan/go/src/github.com/ocmdev/rita/analysis/beacon/beacon_test.go:29 +0x66
testing.tRunner(0xc4200fa0f0, 0x123a950)
	/usr/local/Cellar/go/1.9.2/libexec/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
	/usr/local/Cellar/go/1.9.2/libexec/src/testing/testing.go:789 +0x2de
FAIL	github.com/ocmdev/rita/analysis/beacon	0.030s
```

**Comment by SamuelCarroll** [comment]
What's happening in the test for `f00f663` is that if the build number is "undefined" we can't continue building and that causes an automatic fail for any test. I don't now why it works in `aedfaae` though...

**Comment by ethack** [comment]
Nice find!
I know RITA has code that depends on the version number and will cause issues without it.  I'm not sure how RITA gets built when the tests are run but I'm betting it's missing the compiled-in version number.

**Comment by SamuelCarroll** [comment]
So with the two tests that fail, this may be caused by changes in how we find beacons. I'll need to double check the test cases and modify either what each test is supposed to do or make new tests that cover those cases...

**Comment by ethack** [comment]
I think we should be able to close this issue now.  Zalgo did some work on the tests a little while ago too and they are all passing in the master branch.

https://github.com/activecm/rita/pull/212
https://github.com/activecm/rita/pull/214
