### ISSUE TITLE
Helpful error message if import path doesn't exist

### ISSUE THREAD

**Issue by ethack** [activecm/rita#345]
Currently, if you try to import a directory that doesn't exist RITA spits out a panic and trace message like the following:

```
rita import /does/not/exist/vsagent vsagent
[+] Importing /does/not/exist/vsagent
	[-] Finding files to parse
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/activecm/rita/parser.(*FSImporter).Run(0xc0000e89c0, 0xb15940, 0xc00024e850)
	/go/src/github.com/activecm/rita/parser/fsimporter.go:85 +0xe0c
github.com/activecm/rita/commands.doImport(0xc000116f20, 0x0, 0x0)
	/go/src/github.com/activecm/rita/commands/import.go:68 +0x38b
github.com/activecm/rita/commands.init.2.func1(0xc000116f20, 0x0, 0x0)
	/go/src/github.com/activecm/rita/commands/import.go:28 +0x2f
github.com/activecm/rita/vendor/github.com/urfave/cli.HandleAction(0x98e020, 0xa95b50, 0xc000116f20, 0xc000034800, 0x0)
	/go/src/github.com/activecm/rita/vendor/github.com/urfave/cli/app.go:490 +0xc8
github.com/activecm/rita/vendor/github.com/urfave/cli.Command.Run(0xa6cb20, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0xa8237f, 0x26, 0xa8f788, ...)
	/go/src/github.com/activecm/rita/vendor/github.com/urfave/cli/command.go:210 +0x990
github.com/activecm/rita/vendor/github.com/urfave/cli.(*App).Run(0xc0000b9a00, 0xc00001e0c0, 0x4, 0x4, 0x0, 0x0)
	/go/src/github.com/activecm/rita/vendor/github.com/urfave/cli/app.go:255 +0x687
main.main()
	/go/src/github.com/activecm/rita/rita.go:29 +0x129
```

Rita should instead detect if the directory exists and print a nice error message to the user rather than the cryptic error above.

Related:
- #327 
- #346

**Comment by lisaSW** [comment]
Addressed in v3 branch
