### ISSUE TITLE
Handle error when no new files are found to import

### ISSUE THREAD

**Issue by ethack** [activecm/rita#346]
Currently, if you import a directory into a dataset and then try to import the same directory again (without adding new log files) it prints out an error similar to the following:

```
# The same command was run immediately prior so that vsagent database already exists and all log files are in it
rita import activecm/sample-data/bro/vsagent vsagent
[+] Importing activecm/sample-data/bro/vsagent
	[-] Finding files to parse
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/activecm/rita/parser.(*FSImporter).Run(0xc0001d0360, 0xb15960, 0xc000252310)
	/go/src/github.com/activecm/rita/parser/fsimporter.go:85 +0xe0c
github.com/activecm/rita/commands.doImport(0xc000127340, 0x0, 0x0)
	/go/src/github.com/activecm/rita/commands/import.go:68 +0x38b
github.com/activecm/rita/commands.init.2.func1(0xc000127340, 0x0, 0x0)
	/go/src/github.com/activecm/rita/commands/import.go:28 +0x2f
github.com/activecm/rita/vendor/github.com/urfave/cli.HandleAction(0x98e020, 0xa95b60, 0xc000127340, 0xc0000ae700, 0x0)
	/go/src/github.com/activecm/rita/vendor/github.com/urfave/cli/app.go:490 +0xc8
github.com/activecm/rita/vendor/github.com/urfave/cli.Command.Run(0xa6cb20, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0xa82390, 0x26, 0xa8f799, ...)
	/go/src/github.com/activecm/rita/vendor/github.com/urfave/cli/command.go:210 +0x990
github.com/activecm/rita/vendor/github.com/urfave/cli.(*App).Run(0xc0000cbba0, 0xc0000b0040, 0x4, 0x4, 0x0, 0x0)
	/go/src/github.com/activecm/rita/vendor/github.com/urfave/cli/app.go:255 +0x687
main.main()
	/go/src/github.com/activecm/rita/rita.go:29 +0x129
```

This error should be handled.  A useful message should be printed to the user such as "All log files have already been imported into the specified dataset."

Related
- #327 
- #345

**Comment by lisaSW** [comment]
Addressed in v3 branch
